### ISSUE TITLE
frida.TransportError: the connection is closed

### ISSUE THREAD

**Issue by geans** [frida/frida-core#200]
Hello, I have the following issue to execute the example from [frida-site](https://www.frida.re/docs/examples/android/)
I did test with Python 2 and 3, but has a same problem.

Output:

```
... $ python ctf.py 
[*] Running CTF
Traceback (most recent call last):
  File "ctf.py", line 37, in <module>
    script.load()
  File "/usr/lib/python2.7/dist-packages/frida/core.py", line 192, in load
    self._impl.load()
frida.TransportError: the connection is closed
```

**Comment by geans** [comment]
Work with System Image: Google API level **28**
