### ISSUE TITLE
jdwp injector won't work

### ISSUE THREAD

**Issue by mr-m0nst3r** [frida/frida-core#207]
Hi there, I'm following this post, but can't inject gadget into the app:
[https://koz.io/library-injection-for-debuggable-android-apps/](https://koz.io/library-injection-for-debuggable-android-apps/)

```shell
$ ./jdwp-lib-injector.sh frida-gadget-12.1.0-android-arm.so
[**] Android JDWP library injector by @ikoz
[**] Pushing frida-gadget-12.1.0-android-arm.so to /data/local/tmp/
frida-gadget-12.1.0-android-arm.so: 1 file pushed. 4.9 MB/s (12222000 bytes in 2.369s)
[**] Retrieving pid of running JDWP-enabled app
./jdwp-lib-injector.sh: line 14: kill: (1552) - No such process
[**] JDWP pid is /var/tmp/jdwpPidFile-1535445333. Will forward tcp:8700 to jdwp:31732
[**] Starting jdwp-shellifier.py to load library
[-] Exception: Received errcode 99
Traceback (most recent call last):
  File "jdwp-shellifier.py", line 761, in <module>
    cli.start()
  File "jdwp-shellifier.py", line 180, in start
    self.allclasses()
  File "jdwp-shellifier.py", line 253, in allclasses
    buf = self.read_reply()
  File "jdwp-shellifier.py", line 102, in read_reply
    raise Exception("Received errcode %d" % errcode)
Exception: Received errcode 99
[**] Running frida-ps -U. If you see 'Gadget' then all worked fine!
Failed to enumerate processes: unable to connect to remote frida-server: Unable to connect (connection refused)
``` 

env:
```
android version: 4.4

$ adb shell getprop ro.product.cpu.abi
armeabi-v7a

$ frida-ls-devices 
Id                                        Type    Name            
----------------------------------------  ------  ----------------
local                                     local   Local System    
e8caced7                                  usb     Samsung SM-A3009 <<<<this is the cellphone
eec3dxx036xxx495xx6ba  usb     iPhone      <<<< this is my charging iphone    
tcp                                       remote  Local TCP     

```

Any clue what's going on??

**Comment by shalouzx** [comment]
hi,  i have met the similar problem , i used the python script as you metioned ,the different thing is that i injected my own so file, it goes very well, all the log in the console is the same with the log in the article, but my so was not copied in the target path. so i don't know what i did wrong. Have you figured out this problem?
ps:
i run a debuggable app on anrdoid phone, i run a console command in the cmd.exe on windows 10.

the log goes as followed:
[+] Targeting '127.0.0.1:8700'
[+] Reading settings for 'Dalvik - 1.6.0'
[+] Found Runtime class: id=10da
[+] Found Runtime.getRuntime(): id=701bce80
[+] Created break event id=20000000
[+] Waiting for an event on 'android.app.Activity.onCreate'
[+] Received matching event from thread 0x1353
[+] getPackageMethod(): 'com.Shalou.TestInjectDll'
[*] Copying library from /data/local/tmp/libGPUGraphicsTools.so to /data/data/com.Shalou.TestInjectDll/lib/libGPUGraphicsTools.so
[+] Selected payload 'cp /data/local/tmp/libGPUGraphicsTools.so /data/data/com.Shalou.TestInjectDll/lib/libGPUGraphicsTools.so'
[+] Command string object created id:1356
[+] Runtime.getRuntime() returned context id:0x1357
[+] found Runtime.exec(): id=701bcf80
[+] Runtime.exec() successful, retId=1358
[*] Executing Runtime.load(/data/data/com.Shalou.TestInjectDll/lib/libGPUGraphicsTools.so)
[+] Runtime.load(/data/data/com.Shalou.TestInjectDll/lib/libGPUGraphicsTools.so) probably successful
[*] Library should now be loaded
[!] Command successfully executed

**Comment by mr-m0nst3r** [comment]
@shalouzx Hi there,

I'm using another method to inject so file.
Customized AOSP android, I can configure which app load which so file when start up.

Sorry that I can't help with this.
