### ISSUE TITLE
Vala compilator fails to properly handle Gum.Address values (uint64_t)

### ISSUE THREAD

**Issue by cbayet** [frida/frida-core#209]
Last few days I played a bit with the new fork mechanism, child gating.

I've been trying on x86_64, which worked fine, then I tried on x86, and I couldn't pass the enable_child_gating() python API.
It fails with this stack trace:

```
[Frida ERROR] frida-core/lib/agent/agent.vala:1945:_frida_agent_detect_libc_name: assertion failed: (libc_name != null)
Traceback (most recent call last):
  File "fork_test.py", line 92, in <module>
    session.enable_child_gating()
  File "/home/fafa/.local/lib/python2.7/site-packages/frida/core.py", line 142, in enable_child_gating
    self._impl.enable_child_gating()
```

So I searched where this assert failed, and it happens in the function "_detect_libc_name" in agent.vala:
https://github.com/frida/frida-core/blob/master/lib/agent/agent.vala#L1919

I put some printf here, with the %p modifier, to print me the base_address, the base_address + the size, and the searched libc address at each iteration, and I got an input like:

```
[...]
libc_addr :0xb75f2570
range base: 0xb7546000
range end: 0xb76fa000
[...]
```

So as you could see,it's totally in, but I used %p modifier, so casted the values on "void *", which is 32 bits on x86...
So I try without any cast, and I use the %llu modifier, since Gum.Address are uint64_t.

And this is what I got:

```
[...]
libc_addr: 18446744072491050352 (which gives 0xffffffffb75f2570)
range base: 3075760128
range end: 3077545984
[...]
```

So the libc_addr is definitely wrong. How can this happen ?

So I finally decide to reverse the function to see how it's compiled, and here it is:

```
mov     eax, ds:(opendir_ptr - 1096000h)[ebx]
cdq            // <<< wut
mov     [esi+8], eax
push    edx
push    eax
```

The compiler decided to sign-extend the value of the pointer, even if it's registered as an uint64_t in the code.
And that's definitely why the research fails.

I have no idea why this happen, and you are surely more experienced with vala than me.
Can you explain and fix this ?

Thanks !

**Comment by oleavr** [comment]
Nice catch! Vala compiles to C, where arithmetic and casts are translated 1:1, so for the code above it generates:

```C
#line 1922 "../../../frida-core/lib/agent/agent.vala"
	_data7_->address_in_libc = (GumAddress) opendir;
```

With Clang on macOS/x86 this becomes:

<img width="623" alt="screen shot 2018-09-05 at 13 46 53" src="https://user-images.githubusercontent.com/735197/45091273-2ef2ec80-b112-11e8-933e-a19a2f00b83e.png">

I.e.:

```asm
mov eax, dword [edi + 0xe37877]
```

So this probably means GCC is treating function pointers a bit differently when casting them to unsigned 64-bit values. We should be able to solve that by first casting to `size_t` and then to `Gum.Address`.

**Comment by oleavr** [comment]
Hmm, I strongly suspect that GCC doesn't know what `opendir` is due to a missing include, and it assumes it's an `int` and this is what's causing this.

**Comment by cbayet** [comment]
Ok, did a quick test and gcc doesn't know how to convert a 32 bit pointer in unsigned long long:

See this code:

```
#include <dirent.h>
#include <stdio.h>

int main(void)
{
    unsigned long long ptr =(unsigned long long) opendir;
    printf("opendir %%p is %p\n", opendir);
    printf("opendir is %llu\n", opendir);
}
```


results in 64 and 32 bits:

```
➜  /tmp gcc opendir.c  -o opendir      
➜  /tmp ./opendir
opendir %p is 0x7f500bceb8f0
opendir is 139981772208368
➜  /tmp gcc opendir.c -m32 -o opendir32
opendir.c: In function ‘main’:
opendir.c:6:29: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     unsigned long long ptr =(unsigned long long) opendir;
                             ^
➜  /tmp ./opendir32 
opendir %p is 0xf7dc2bf0
opendir is 18445631698518158320
```

gcc outputs a warning for converting a 32 bits pointer to an unsigned long long, and sign extend the pointer...

Why don't we see the warning in the compilation ?
And how this should be fixed ?

**Comment by cbayet** [comment]
Ok, did a quick test and gcc doesn't know how to convert a 32 bit pointer in unsigned long long:

See this code:

```
#include <dirent.h>
#include <stdio.h>

int main(void)
{
    unsigned long long ptr =(unsigned long long) opendir;
    printf("opendir %%p is %p\n", ptr);
    printf("opendir is %llu\n", ptr);
}
```


results in 64 and 32 bits:

```
➜  /tmp gcc opendir.c  -o opendir      
➜  /tmp ./opendir
opendir %p is 0x7f500bceb8f0
opendir is 139981772208368
➜  /tmp gcc opendir.c -m32 -o opendir32
opendir.c: In function ‘main’:
opendir.c:6:29: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     unsigned long long ptr =(unsigned long long) opendir;
                             ^
➜  /tmp ./opendir32 
opendir %p is 0xf7dc2bf0
opendir is 18445631698518158320
```

gcc outputs a warning for converting a 32 bits pointer to an unsigned long long, and sign extend the pointer...

Why don't we see the warning in the compilation ?
And how this should be fixed ?

Dumb question, since this is not the first time I got issue with uint64_t as pointers:
Why did you made GumAddress a guint64_t, and not a gsize (or similar), so it always have the right size for a given architecture ?

**Comment by oleavr** [comment]
> Why don't we see the warning in the compilation ?

Warnings are disabled by Meson for Vala-generated code. This is probably temporary – until the Vala compiler generates warning-free code.

> Why did you made GumAddress a guint64_t, and not a gsize (or similar), so it always have the right size for a given architecture ?

It's so a 32-bit process can work with memory addresses of a remote process that might be 64-bit. E.g. the Darwin-specific APIs in Gum, used by -core to implement the Darwin injector.
