### ISSUE TITLE
Building "frida-core" fails on Windows 10 👎

### ISSUE THREAD

**Issue by AxDSan** [frida/frida-core#317]
`
1>------ Build started: Project: frida-core, Configuration: Debug Win32 ------
1>Serializing Winjector resources
1>Serializing Agent resources
1>Compiling vala code
1>Traceback (most recent call last):
1>  File "D:\DevStuff\WebDev\Node\frida\frida-core\src\api\generate.py", line 411, in <module>
1>    main()
1>  File "D:\DevStuff\WebDev\Node\frida\frida-core\src\api\generate.py", line 13, in main
1>    parser.add_argument('api_vala', metavar='/path/to/frida.vala', type=argparse.FileType('r', encoding='UTF-8'))
1>TypeError: __init__() got an unexpected keyword argument 'encoding'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1.
1>Done building project "frida-core.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 21 up-to-date, 0 skipped ==========
`

**Comment by AxDSan** [comment]
Replacing:
`parser.add_argument('api_vala', metavar='/path/to/frida.vala', type=argparse.FileType('r', encoding='UTF-8'))`

with:

`parser.add_argument('api_vala', metavar='/path/to/frida.vala', type=argparse.FileType('r', 0))`

Seems to serve as a workaround.
