### ISSUE TITLE
Unable to attach on M1

### ISSUE THREAD

**Issue by anoane** [frida/frida-core#465]
I made a script last year to spawn, attach and hook some applications on Mac M1 and it used to work just fine

device = frida.get_local_device()
pid = device.spawn('/Applications/xyz')
session = device.attach(pid)

But now after the latest MacOS and Frida updates I get:

Traceback (most recent call last):
  File "/Users/anon/xyz.py", line xyz, in <module>
    session = device.attach(pid)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/frida/core.py", line 1010, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
frida.NotSupportedError: unexpected error while probing dyld of target process

Mac M1 Pro
MacOS 13.4 Beta (22F5027f)
Python 3.9.11
frida 16.0.14
frida-tools 12.1.1

**Comment by landrufang** [comment]
on macos 14 , application crashed when i use device.spawn. and i have already disable sip.
if i launch app manually , and device.attach , it works fine.  any idea ?
